import { ClerkProvider } from "@clerk/nextjs";
import { type AppType } from "next/app";
import Head from "next/head";
import Modal from "react-modal";
import { api } from "~/utils/api";
import "~/styles/globals.css";

Modal.setAppElement("#modal");
const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Tweeter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClerkProvider {...pageProps}>
        <Component {...pageProps} />)
        <div id="modal" />
      </ClerkProvider>
    </>
  );
};

export default api.withTRPC(MyApp);