import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();

  console.log(user.user?.id);
  if (isLoading) return <h1>LOADING...</h1>;

  if (!data) return <h1>ERROR</h1>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {user.isSignedIn ? (
          <div>
            <SignInButton /> <br />
            <SignOutButton />
            {data.map((post) => (
              <h1 key={post.id}>{post.content}</h1>
            ))}
          </div>
        ) : (
          <SignInButton />
        )}
      </main>
    </>
  );
};

export default Home;